
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # Port SMTP
      - "8025:8025"  # Interface Web
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - symfony

###< symfony/mailer ###
