services:
  php:
    build:
      context: .
    container_name: musicoria_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - database
    networks:
      - symfony

  database:
    image: mysql:8.0
    container_name: musicoria_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicoria
      MYSQL_USER: musicoria_user
      MYSQL_PASSWORD: musicoria_pass
    networks:
      - symfony


networks:
  symfony:
    driver: bridge
