services:
  php:
    build:
      context: .
    container_name: musicoria_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - database
    networks:
      - symfony

  database:
    image: mysql:8.0
    container_name: musicoria_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicoria
      MYSQL_USER: musicoria_user
      MYSQL_PASSWORD: musicoria_pass
    networks:
      - symfony

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: musicoria_phpmyadmin
    environment:
      PMA_HOST: database  # Le nom du service MySQL dans le même réseau
      PMA_PORT: 3306      # Port MySQL par défaut
    ports:
      - "8080:80"         # Expose le port 8080 de votre machine vers le port 80 du conteneur phpMyAdmin
    depends_on:
      - database
    networks:
      - symfony


networks:
  symfony:
    driver: bridge
